# ************************************************************************
#  @author:     Andreas Kaeberlein
#  @copyright:  Copyright 2021
#  @credits:    AKAE
#
#  @license:    BSDv3
#  @maintainer: Andreas Kaeberlein
#  @email:      andreas.kaeberlein@web.de
#
#  @file:       unittest.yml
#  @date:       2021-08-25
#
#  @brief:      runs test and deploy
#
# ************************************************************************


name: Unittest

on:
  push:
    paths-ignore:
      - 'doc/**'
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GHDL_OPTS: "--std=93c --ieee=synopsys --time-resolution=ps --workdir=./sim/work"
    steps:
      - uses: actions/checkout@v1
      - uses: ghdl/setup-ghdl-ci@nightly
        with:
          backend: mcode
      - name: Prepare
        run: |
          ghdl --version
          mkdir -p ./sim/work
      - name: generic_spi_master_inp_filter_tb
        run: |
          ghdl -a ${GHDL_OPTS} ./hdl/generic_spi_master_inp_filter.vhd
          ghdl -a ${GHDL_OPTS} ./tb/generic_spi_master_inp_filter_tb.vhd
          ((ghdl -r ${GHDL_OPTS} generic_spi_master_inp_filter_tb -gDO_ALL_TEST=True) || if [ $? -ne 0 ]; then echo "[ FAIL ]   generic_spi_master_inp_filter"; exit 1; fi)
      - name: generic_spi_master_mode_0_3_tb
        run: |
          ghdl -a ${GHDL_OPTS} ./hdl/generic_spi_master_inp_filter.vhd
          ghdl -a ${GHDL_OPTS} ./hdl/generic_spi_master.vhd
          ghdl -a ${GHDL_OPTS} ./tb/generic_spi_master_mode_0_3_tb.vhd
          ((ghdl -r ${GHDL_OPTS} generic_spi_master_mode_0_3_tb -gDO_ALL_TEST=True -gCLK_DIV2=1 -gSPI_MODE=0) || if [ $? -ne 0 ]; then echo "[ FAIL ]   generic_spi_master_mode_0_3_tb"; exit 1; fi)
          ((ghdl -r ${GHDL_OPTS} generic_spi_master_mode_0_3_tb -gDO_ALL_TEST=True -gCLK_DIV2=2 -gSPI_MODE=0) || if [ $? -ne 0 ]; then echo "[ FAIL ]   generic_spi_master_mode_0_3_tb"; exit 1; fi)
          ((ghdl -r ${GHDL_OPTS} generic_spi_master_mode_0_3_tb -gDO_ALL_TEST=True -gCLK_DIV2=3 -gSPI_MODE=0) || if [ $? -ne 0 ]; then echo "[ FAIL ]   generic_spi_master_mode_0_3_tb"; exit 1; fi)
          ((ghdl -r ${GHDL_OPTS} generic_spi_master_mode_0_3_tb -gDO_ALL_TEST=True -gCLK_DIV2=1 -gSPI_MODE=1) || if [ $? -ne 0 ]; then echo "[ FAIL ]   generic_spi_master_mode_0_3_tb"; exit 1; fi)
          ((ghdl -r ${GHDL_OPTS} generic_spi_master_mode_0_3_tb -gDO_ALL_TEST=True -gCLK_DIV2=2 -gSPI_MODE=1) || if [ $? -ne 0 ]; then echo "[ FAIL ]   generic_spi_master_mode_0_3_tb"; exit 1; fi)
          ((ghdl -r ${GHDL_OPTS} generic_spi_master_mode_0_3_tb -gDO_ALL_TEST=True -gCLK_DIV2=3 -gSPI_MODE=1) || if [ $? -ne 0 ]; then echo "[ FAIL ]   generic_spi_master_mode_0_3_tb"; exit 1; fi)
          ((ghdl -r ${GHDL_OPTS} generic_spi_master_mode_0_3_tb -gDO_ALL_TEST=True -gCLK_DIV2=1 -gSPI_MODE=2) || if [ $? -ne 0 ]; then echo "[ FAIL ]   generic_spi_master_mode_0_3_tb"; exit 1; fi)
          ((ghdl -r ${GHDL_OPTS} generic_spi_master_mode_0_3_tb -gDO_ALL_TEST=True -gCLK_DIV2=2 -gSPI_MODE=2) || if [ $? -ne 0 ]; then echo "[ FAIL ]   generic_spi_master_mode_0_3_tb"; exit 1; fi)
          ((ghdl -r ${GHDL_OPTS} generic_spi_master_mode_0_3_tb -gDO_ALL_TEST=True -gCLK_DIV2=3 -gSPI_MODE=2) || if [ $? -ne 0 ]; then echo "[ FAIL ]   generic_spi_master_mode_0_3_tb"; exit 1; fi)
          ((ghdl -r ${GHDL_OPTS} generic_spi_master_mode_0_3_tb -gDO_ALL_TEST=True -gCLK_DIV2=1 -gSPI_MODE=3) || if [ $? -ne 0 ]; then echo "[ FAIL ]   generic_spi_master_mode_0_3_tb"; exit 1; fi)
          ((ghdl -r ${GHDL_OPTS} generic_spi_master_mode_0_3_tb -gDO_ALL_TEST=True -gCLK_DIV2=2 -gSPI_MODE=3) || if [ $? -ne 0 ]; then echo "[ FAIL ]   generic_spi_master_mode_0_3_tb"; exit 1; fi)
          ((ghdl -r ${GHDL_OPTS} generic_spi_master_mode_0_3_tb -gDO_ALL_TEST=True -gCLK_DIV2=3 -gSPI_MODE=3) || if [ $? -ne 0 ]; then echo "[ FAIL ]   generic_spi_master_mode_0_3_tb"; exit 1; fi)
      - name: generic_spi_master_HC594_HC165_tb
        run: |
          ghdl -a ${GHDL_OPTS} ./hdl/generic_spi_master_inp_filter.vhd
          ghdl -a ${GHDL_OPTS} ./hdl/generic_spi_master.vhd
          ghdl -a ${GHDL_OPTS} ./tb/HC165.vhd
          ghdl -a ${GHDL_OPTS} ./tb/HC594.vhd
          ghdl -a ${GHDL_OPTS} ./tb/generic_spi_master_HC594_HC165_tb.vhd
          ((ghdl -r ${GHDL_OPTS} generic_spi_master_HC594_HC165_tb -gDO_ALL_TEST=True) || if [ $? -ne 0 ]; then echo "[ FAIL ]   generic_spi_master_HC594_HC165_tb"; exit 1; fi)
